# Чтение и запись данных, часть 2

## Практическая работа

### Описание практической работы и формат сдачи

Выполните предложенные задачи: сохраните блокнот отдельно себе на диск и после этого пишите код в ячейках под задачами. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) загрузите в личный кабинет и отправьте на проверку.

### Задача 1

Используя сервис WeatherAPI, получите прогноз погоды в Лондоне на следующие 2 дня. Ответ преобразуйте к типу JSON.

In [3]:
import urllib.request as req
import json

url = "https://hi.tander.ru/auth/realms/tander-api-merch/.well-known/openid-configuration"

# Создаем заголовки, чтобы "притвориться" браузером
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

# Создаем объект запроса с заголовками
request = req.Request(url, headers=headers)

# Выполняем запрос
session = req.urlopen(request)
response = session.read().decode()
session.close()
data = json.loads(response)
print(data)

{'issuer': 'https://hi.tander.ru/auth/realms/tander-api-merch', 'authorization_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/auth', 'token_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/token', 'introspection_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/token/introspect', 'userinfo_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/userinfo', 'end_session_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/logout', 'frontchannel_logout_session_supported': True, 'frontchannel_logout_supported': True, 'jwks_uri': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/certs', 'check_session_iframe': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/login-status-iframe.html', 'grant_types_supported': ['authorization_code', 'implicit', 'refresh_token', 'password', 'client_credentials', 'urn:openid:params:grant-type:ciba', 'urn:ietf:params:oauth:grant-type:device_code'], 'acr_values_supported': ['0', '1'], 'response_types_supported': ['code', 'none', 'id_token', 'token', 'id_token token', 'code id_token', 'code token', 'code id_token token'], 'subject_types_supported': ['public', 'pairwise'], 'id_token_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512'], 'id_token_encryption_alg_values_supported': ['RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5'], 'id_token_encryption_enc_values_supported': ['A256GCM', 'A192GCM', 'A128GCM', 'A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512'], 'userinfo_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512', 'none'], 'userinfo_encryption_alg_values_supported': ['RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5'], 'userinfo_encryption_enc_values_supported': ['A256GCM', 'A192GCM', 'A128GCM', 'A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512'], 'request_object_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512', 'none'], 'request_object_encryption_alg_values_supported': ['RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5'], 'request_object_encryption_enc_values_supported': ['A256GCM', 'A192GCM', 'A128GCM', 'A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512'], 'response_modes_supported': ['query', 'fragment', 'form_post', 'query.jwt', 'fragment.jwt', 'form_post.jwt', 'jwt'], 'registration_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/clients-registrations/openid-connect', 'token_endpoint_auth_methods_supported': ['private_key_jwt', 'client_secret_basic', 'client_secret_post', 'tls_client_auth', 'client_secret_jwt'], 'token_endpoint_auth_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512'], 'introspection_endpoint_auth_methods_supported': ['private_key_jwt', 'client_secret_basic', 'client_secret_post', 'tls_client_auth', 'client_secret_jwt'], 'introspection_endpoint_auth_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512'], 'authorization_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512'], 'authorization_encryption_alg_values_supported': ['RSA-OAEP', 'RSA-OAEP-256', 'RSA1_5'], 'authorization_encryption_enc_values_supported': ['A256GCM', 'A192GCM', 'A128GCM', 'A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512'], 'claims_supported': ['aud', 'sub', 'iss', 'auth_time', 'name', 'given_name', 'family_name', 'preferred_username', 'email', 'acr'], 'claim_types_supported': ['normal'], 'claims_parameter_supported': True, 'scopes_supported': ['openid', 'phone', 'address', 'web-origins', 'microprofile-jwt', 'offline_access', 'email', 'profile', 'roles', 'acr'], 'request_parameter_supported': True, 'request_uri_parameter_supported': True, 'require_request_uri_registration': True, 'code_challenge_methods_supported': ['plain', 'S256'], 'tls_client_certificate_bound_access_tokens': True, 'revocation_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/revoke', 'revocation_endpoint_auth_methods_supported': ['private_key_jwt', 'client_secret_basic', 'client_secret_post', 'tls_client_auth', 'client_secret_jwt'], 'revocation_endpoint_auth_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'HS256', 'HS512', 'ES256', 'RS256', 'HS384', 'ES512', 'PS256', 'PS512', 'RS512'], 'backchannel_logout_supported': True, 'backchannel_logout_session_supported': True, 'device_authorization_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/auth/device', 'backchannel_token_delivery_modes_supported': ['poll', 'ping'], 'backchannel_authentication_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/ext/ciba/auth', 'backchannel_authentication_request_signing_alg_values_supported': ['PS384', 'ES384', 'RS384', 'ES256', 'RS256', 'ES512', 'PS256', 'PS512', 'RS512'], 'require_pushed_authorization_requests': False, 'pushed_authorization_request_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/ext/par/request', 'mtls_endpoint_aliases': {'token_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/token', 'revocation_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/revoke', 'introspection_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/token/introspect', 'device_authorization_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/auth/device', 'registration_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/clients-registrations/openid-connect', 'userinfo_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/userinfo', 'pushed_authorization_request_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/ext/par/request', 'backchannel_authentication_endpoint': 'https://hi.tander.ru/auth/realms/tander-api-merch/protocol/openid-connect/ext/ciba/auth'}, 'authorization_response_iss_parameter_supported': True}

In [1]:
with req.urlopen(url) as session:
  response1 = session.read().decode()

response1

NameError: name 'req' is not defined

In [62]:

import urllib.request as req
import json

API_KEY = "83976e6bce8d4fe8980142043251509"  # нужно получить на weatherapi.com
city = "London"
days = 2

url = f"http://api.weatherapi.com/v1/forecast.json?key={API_KEY}&q={city}&days={days}"

session = req.urlopen(url)
response = session.read().decode()
session.close()
data = json.loads(response)
print(data)

{'location': {'name': 'London', 'region': 'City of London, Greater London', 'country': 'United Kingdom', 'lat': 51.5171, 'lon': -0.1062, 'tz_id': 'Europe/London', 'localtime_epoch': 1758523947, 'localtime': '2025-09-22 07:52'}, 'current': {'last_updated_epoch': 1758523500, 'last_updated': '2025-09-22 07:45', 'temp_c': 8.3, 'temp_f': 46.9, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 9.4, 'wind_kph': 15.1, 'wind_degree': 12, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.3, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 81, 'cloud': 0, 'feelslike_c': 5.8, 'feelslike_f': 42.4, 'windchill_c': 7.6, 'windchill_f': 45.6, 'heatindex_c': 9.7, 'heatindex_f': 49.5, 'dewpoint_c': 4.1, 'dewpoint_f': 39.3, 'vis_km': 10.0, 'vis_miles': 6.0, 'uv': 0.0, 'gust_mph': 13.3, 'gust_kph': 21.5, 'short_rad': 0.08, 'diff_rad': 0.03, 'dni': 0.0, 'gti': 0.03}, 'forecast': {'forecastday': [{'date': '2025-09-22', 'date_epoch': 1758499200, 'day': {'maxtemp_c': 16.5, 'maxtemp_f': 61.8, 'mintemp_c': 8.9, 'mintemp_f': 48.1, 'avgtemp_c': 12.4, 'avgtemp_f': 54.3, 'maxwind_mph': 11.4, 'maxwind_kph': 18.4, 'totalprecip_mm': 0.0, 'totalprecip_in': 0.0, 'totalsnow_cm': 0.0, 'avgvis_km': 10.0, 'avgvis_miles': 6.0, 'avghumidity': 53, 'daily_will_it_rain': 0, 'daily_chance_of_rain': 0, 'daily_will_it_snow': 0, 'daily_chance_of_snow': 0, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'uv': 0.5}, 'astro': {'sunrise': '06:47 AM', 'sunset': '06:58 PM', 'moonrise': '07:26 AM', 'moonset': '06:57 PM', 'moon_phase': 'Waxing Crescent', 'moon_illumination': 0, 'is_moon_up': 0, 'is_sun_up': 0}, 'hour': [{'time_epoch': 1758495600, 'time': '2025-09-22 00:00', 'temp_c': 10.2, 'temp_f': 50.4, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 8.1, 'wind_kph': 13.0, 'wind_degree': 19, 'wind_dir': 'NNE', 'pressure_mb': 1024.0, 'pressure_in': 30.25, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 68, 'cloud': 8, 'feelslike_c': 8.4, 'feelslike_f': 47.2, 'windchill_c': 8.4, 'windchill_f': 47.2, 'heatindex_c': 10.2, 'heatindex_f': 50.4, 'dewpoint_c': 4.5, 'dewpoint_f': 40.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.7, 'gust_kph': 18.8, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758499200, 'time': '2025-09-22 01:00', 'temp_c': 9.9, 'temp_f': 49.8, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 8.1, 'wind_kph': 13.0, 'wind_degree': 14, 'wind_dir': 'NNE', 'pressure_mb': 1025.0, 'pressure_in': 30.25, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 71, 'cloud': 20, 'feelslike_c': 8.0, 'feelslike_f': 46.4, 'windchill_c': 8.0, 'windchill_f': 46.4, 'heatindex_c': 9.9, 'heatindex_f': 49.8, 'dewpoint_c': 4.9, 'dewpoint_f': 40.7, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.8, 'gust_kph': 18.9, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758502800, 'time': '2025-09-22 02:00', 'temp_c': 9.7, 'temp_f': 49.4, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 8.9, 'wind_kph': 14.4, 'wind_degree': 6, 'wind_dir': 'N', 'pressure_mb': 1024.0, 'pressure_in': 30.25, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 73, 'cloud': 11, 'feelslike_c': 7.6, 'feelslike_f': 45.7, 'windchill_c': 7.6, 'windchill_f': 45.7, 'heatindex_c': 9.7, 'heatindex_f': 49.4, 'dewpoint_c': 5.0, 'dewpoint_f': 41.0, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.3, 'gust_kph': 21.3, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758506400, 'time': '2025-09-22 03:00', 'temp_c': 9.4, 'temp_f': 48.9, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 8.9, 'wind_kph': 14.4, 'wind_degree': 9, 'wind_dir': 'N', 'pressure_mb': 1025.0, 'pressure_in': 30.26, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 73, 'cloud': 11, 'feelslike_c': 7.3, 'feelslike_f': 45.1, 'windchill_c': 7.3, 'windchill_f': 45.1, 'heatindex_c': 9.4, 'heatindex_f': 48.9, 'dewpoint_c': 4.9, 'dewpoint_f': 40.7, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.4, 'gust_kph': 21.5, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758510000, 'time': '2025-09-22 04:00', 'temp_c': 9.2, 'temp_f': 48.6, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 9.2, 'wind_kph': 14.8, 'wind_degree': 10, 'wind_dir': 'N', 'pressure_mb': 1025.0, 'pressure_in': 30.27, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 73, 'cloud': 6, 'feelslike_c': 7.0, 'feelslike_f': 44.6, 'windchill_c': 7.0, 'windchill_f': 44.6, 'heatindex_c': 9.3, 'heatindex_f': 48.7, 'dewpoint_c': 4.6, 'dewpoint_f': 40.4, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.9, 'gust_kph': 22.3, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758513600, 'time': '2025-09-22 05:00', 'temp_c': 9.0, 'temp_f': 48.3, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 9.4, 'wind_kph': 15.1, 'wind_degree': 7, 'wind_dir': 'N', 'pressure_mb': 1026.0, 'pressure_in': 30.29, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 72, 'cloud': 6, 'feelslike_c': 6.7, 'feelslike_f': 44.1, 'windchill_c': 6.7, 'windchill_f': 44.1, 'heatindex_c': 9.0, 'heatindex_f': 48.3, 'dewpoint_c': 4.3, 'dewpoint_f': 39.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 14.3, 'gust_kph': 23.0, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758517200, 'time': '2025-09-22 06:00', 'temp_c': 8.9, 'temp_f': 48.1, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 9.4, 'wind_kph': 15.1, 'wind_degree': 11, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.3, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 72, 'cloud': 6, 'feelslike_c': 6.6, 'feelslike_f': 43.9, 'windchill_c': 6.6, 'windchill_f': 43.9, 'heatindex_c': 9.0, 'heatindex_f': 48.1, 'dewpoint_c': 4.2, 'dewpoint_f': 39.6, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 14.5, 'gust_kph': 23.3, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758520800, 'time': '2025-09-22 07:00', 'temp_c': 8.3, 'temp_f': 46.9, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 9.4, 'wind_kph': 15.1, 'wind_degree': 12, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.3, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 81, 'cloud': 0, 'feelslike_c': 7.6, 'feelslike_f': 45.6, 'windchill_c': 7.6, 'windchill_f': 45.6, 'heatindex_c': 9.7, 'heatindex_f': 49.5, 'dewpoint_c': 4.1, 'dewpoint_f': 39.3, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.3, 'gust_kph': 21.5, 'uv': 0.0, 'short_rad': 0.08, 'diff_rad': 0.03, 'dni': 0.0, 'gti': 0.03}, {'time_epoch': 1758524400, 'time': '2025-09-22 08:00', 'temp_c': 11.2, 'temp_f': 52.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 10.1, 'wind_kph': 16.2, 'wind_degree': 16, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.33, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 59, 'cloud': 3, 'feelslike_c': 9.3, 'feelslike_f': 48.7, 'windchill_c': 9.3, 'windchill_f': 48.7, 'heatindex_c': 11.2, 'heatindex_f': 52.2, 'dewpoint_c': 3.6, 'dewpoint_f': 38.5, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.8, 'gust_kph': 20.7, 'uv': 0.1, 'short_rad': 60.82, 'diff_rad': 24.19, 'dni': 1734.64, 'gti': 15.68}, {'time_epoch': 1758528000, 'time': '2025-09-22 09:00', 'temp_c': 12.9, 'temp_f': 55.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 11.0, 'wind_kph': 17.6, 'wind_degree': 21, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.33, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 50, 'cloud': 2, 'feelslike_c': 11.2, 'feelslike_f': 52.2, 'windchill_c': 11.2, 'windchill_f': 52.2, 'heatindex_c': 12.9, 'heatindex_f': 55.2, 'dewpoint_c': 2.8, 'dewpoint_f': 37.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.9, 'gust_kph': 20.8, 'uv': 0.2, 'short_rad': 135.72, 'diff_rad': 40.13, 'dni': 527.3, 'gti': 4.98}, {'time_epoch': 1758531600, 'time': '2025-09-22 10:00', 'temp_c': 14.1, 'temp_f': 57.4, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 11.0, 'wind_kph': 17.6, 'wind_degree': 26, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.34, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 43, 'cloud': 0, 'feelslike_c': 12.7, 'feelslike_f': 54.9, 'windchill_c': 12.7, 'windchill_f': 54.9, 'heatindex_c': 14.1, 'heatindex_f': 57.4, 'dewpoint_c': 1.9, 'dewpoint_f': 35.4, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.6, 'gust_kph': 20.3, 'uv': 0.6, 'short_rad': 211.66, 'diff_rad': 51.12, 'dni': 487.59, 'gti': 0.0}, {'time_epoch': 1758535200, 'time': '2025-09-22 11:00', 'temp_c': 15.0, 'temp_f': 59.0, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 10.3, 'wind_kph': 16.6, 'wind_degree': 24, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.33, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 40, 'cloud': 18, 'feelslike_c': 15.0, 'feelslike_f': 59.0, 'windchill_c': 15.0, 'windchill_f': 59.0, 'heatindex_c': 15.0, 'heatindex_f': 59.0, 'dewpoint_c': 1.4, 'dewpoint_f': 34.5, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.8, 'gust_kph': 19.0, 'uv': 1.8, 'short_rad': 281.88, 'diff_rad': 59.13, 'dni': 489.66, 'gti': 0.0}, {'time_epoch': 1758538800, 'time': '2025-09-22 12:00', 'temp_c': 15.8, 'temp_f': 60.5, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 10.1, 'wind_kph': 16.2, 'wind_degree': 20, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.32, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 37, 'cloud': 6, 'feelslike_c': 15.8, 'feelslike_f': 60.5, 'windchill_c': 15.8, 'windchill_f': 60.5, 'heatindex_c': 15.8, 'heatindex_f': 60.5, 'dewpoint_c': 1.3, 'dewpoint_f': 34.3, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.6, 'gust_kph': 18.6, 'uv': 2.8, 'short_rad': 342.19, 'diff_rad': 65.12, 'dni': 504.06, 'gti': 0.0}, {'time_epoch': 1758542400, 'time': '2025-09-22 13:00', 'temp_c': 16.4, 'temp_f': 61.4, 'is_day': 1, 'condition': {'text': 'Partly Cloudy ', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003}, 'wind_mph': 10.7, 'wind_kph': 17.3, 'wind_degree': 18, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.31, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 35, 'cloud': 46, 'feelslike_c': 16.4, 'feelslike_f': 61.4, 'windchill_c': 16.4, 'windchill_f': 61.4, 'heatindex_c': 16.4, 'heatindex_f': 61.4, 'dewpoint_c': 0.9, 'dewpoint_f': 33.7, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.3, 'gust_kph': 19.9, 'uv': 2.0, 'short_rad': 389.81, 'diff_rad': 69.41, 'dni': 527.77, 'gti': 0.0}, {'time_epoch': 1758546000, 'time': '2025-09-22 14:00', 'temp_c': 16.5, 'temp_f': 61.8, 'is_day': 1, 'condition': {'text': 'Partly Cloudy ', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003}, 'wind_mph': 10.7, 'wind_kph': 17.3, 'wind_degree': 16, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.31, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 33, 'cloud': 46, 'feelslike_c': 16.5, 'feelslike_f': 61.8, 'windchill_c': 16.5, 'windchill_f': 61.8, 'heatindex_c': 16.5, 'heatindex_f': 61.8, 'dewpoint_c': 0.2, 'dewpoint_f': 32.4, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.3, 'gust_kph': 19.9, 'uv': 1.4, 'short_rad': 621.02, 'diff_rad': 90.23, 'dni': 851.73, 'gti': 0.0}, {'time_epoch': 1758549600, 'time': '2025-09-22 15:00', 'temp_c': 16.5, 'temp_f': 61.6, 'is_day': 1, 'condition': {'text': 'Partly Cloudy ', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003}, 'wind_mph': 10.3, 'wind_kph': 16.6, 'wind_degree': 19, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.31, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 32, 'cloud': 46, 'feelslike_c': 16.5, 'feelslike_f': 61.6, 'windchill_c': 16.5, 'windchill_f': 61.6, 'heatindex_c': 16.5, 'heatindex_f': 61.6, 'dewpoint_c': -0.2, 'dewpoint_f': 31.6, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.8, 'gust_kph': 19.0, 'uv': 1.5, 'short_rad': 593.06, 'diff_rad': 87.83, 'dni': 846.44, 'gti': 0.0}, {'time_epoch': 1758553200, 'time': '2025-09-22 16:00', 'temp_c': 15.9, 'temp_f': 60.6, 'is_day': 1, 'condition': {'text': 'Partly Cloudy ', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003}, 'wind_mph': 11.4, 'wind_kph': 18.4, 'wind_degree': 14, 'wind_dir': 'NNE', 'pressure_mb': 1026.0, 'pressure_in': 30.31, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 33, 'cloud': 46, 'feelslike_c': 15.9, 'feelslike_f': 60.6, 'windchill_c': 15.9, 'windchill_f': 60.6, 'heatindex_c': 15.9, 'heatindex_f': 60.6, 'dewpoint_c': -0.1, 'dewpoint_f': 31.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.8, 'gust_kph': 22.2, 'uv': 0.8, 'short_rad': 550.56, 'diff_rad': 84.44, 'dni': 879.54, 'gti': 0.0}, {'time_epoch': 1758556800, 'time': '2025-09-22 17:00', 'temp_c': 15.0, 'temp_f': 59.0, 'is_day': 1, 'condition': {'text': 'Partly Cloudy ', 'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png', 'code': 1003}, 'wind_mph': 10.7, 'wind_kph': 17.3, 'wind_degree': 16, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.32, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 37, 'cloud': 48, 'feelslike_c': 15.0, 'feelslike_f': 59.0, 'windchill_c': 15.0, 'windchill_f': 59.0, 'heatindex_c': 15.0, 'heatindex_f': 59.0, 'dewpoint_c': 0.3, 'dewpoint_f': 32.6, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 13.9, 'gust_kph': 22.3, 'uv': 0.4, 'short_rad': 494.96, 'diff_rad': 80.58, 'dni': 970.58, 'gti': 0.0}, {'time_epoch': 1758560400, 'time': '2025-09-22 18:00', 'temp_c': 13.8, 'temp_f': 56.9, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 9.2, 'wind_kph': 14.8, 'wind_degree': 19, 'wind_dir': 'NNE', 'pressure_mb': 1027.0, 'pressure_in': 30.33, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 40, 'cloud': 9, 'feelslike_c': 12.7, 'feelslike_f': 54.8, 'windchill_c': 12.7, 'windchill_f': 54.8, 'heatindex_c': 13.8, 'heatindex_f': 56.9, 'dewpoint_c': 0.5, 'dewpoint_f': 32.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 12.8, 'gust_kph': 20.7, 'uv': 0.1, 'short_rad': 430.53, 'diff_rad': 74.3, 'dni': 1208.15, 'gti': 0.0}, {'time_epoch': 1758564000, 'time': '2025-09-22 19:00', 'temp_c': 12.7, 'temp_f': 54.8, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 8.1, 'wind_kph': 13.0, 'wind_degree': 34, 'wind_dir': 'NE', 'pressure_mb': 1028.0, 'pressure_in': 30.36, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 45, 'cloud': 6, 'feelslike_c': 11.4, 'feelslike_f': 52.6, 'windchill_c': 11.4, 'windchill_f': 52.6, 'heatindex_c': 12.7, 'heatindex_f': 54.8, 'dewpoint_c': 1.0, 'dewpoint_f': 33.8, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 11.7, 'gust_kph': 18.9, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758567600, 'time': '2025-09-22 20:00', 'temp_c': 12.1, 'temp_f': 53.7, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 6.7, 'wind_kph': 10.8, 'wind_degree': 44, 'wind_dir': 'NE', 'pressure_mb': 1029.0, 'pressure_in': 30.37, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 48, 'cloud': 5, 'feelslike_c': 11.0, 'feelslike_f': 51.8, 'windchill_c': 11.0, 'windchill_f': 51.8, 'heatindex_c': 12.1, 'heatindex_f': 53.7, 'dewpoint_c': 1.3, 'dewpoint_f': 34.4, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 9.9, 'gust_kph': 15.9, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758571200, 'time': '2025-09-22 21:00', 'temp_c': 11.6, 'temp_f': 52.9, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 5.8, 'wind_kph': 9.4, 'wind_degree': 38, 'wind_dir': 'NE', 'pressure_mb': 1029.0, 'pressure_in': 30.38, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 51, 'cloud': 7, 'feelslike_c': 10.6, 'feelslike_f': 51.2, 'windchill_c': 10.6, 'windchill_f': 51.2, 'heatindex_c': 11.6, 'heatindex_f': 52.9, 'dewpoint_c': 1.7, 'dewpoint_f': 35.1, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 8.6, 'gust_kph': 13.8, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758574800, 'time': '2025-09-22 22:00', 'temp_c': 11.3, 'temp_f': 52.3, 'is_day': 0, 'condition': {'text': 'Clear ', 'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png', 'code': 1000}, 'wind_mph': 4.9, 'wind_kph': 7.9, 'wind_degree': 42, 'wind_dir': 'NE', 'pressure_mb': 1029.0, 'pressure_in': 30.38, 'precip_mm': 0.0, 'precip_in': 0.0, 'snow_cm': 0.0, 'humidity': 53, 'cloud': 6, 'feelslike_c': 10.6, 'feelslike_f': 51.0, 'windchill_c': 10.6, 'windchill_f': 51.0, 'heatindex_c': 11.3, 'heatindex_f': 52.3, 'dewpoint_c': 2.2, 'dewpoint_f': 35.9, 'will_it_rain': 0, 'chance_of_rain': 0, 'will_it_snow': 0, 'chance_of_snow': 0, 'vis_km': 10.0, 'vis_miles': 6.0, 'gust_mph': 7.1, 'gust_kph': 11.4, 'uv': 0, 'short_rad': 0, 'diff_rad': 0, 'dni': 0, 'gti': 0}, {'time_epoch': 1758578400, 'time': '2025-09-22 23:00', 'temp_c': 10.9, 'temp_f': 51.7, 'is_day': 0, 'condition': {

In [63]:
with req.urlopen(url) as session:
  response1 = session.read().decode()

response1

'{"location":{"name":"London","region":"City of London, Greater London","country":"United Kingdom","lat":51.5171,"lon":-0.1062,"tz_id":"Europe/London","localtime_epoch":1758523947,"localtime":"2025-09-22 07:52"},"current":{"last_updated_epoch":1758523500,"last_updated":"2025-09-22 07:45","temp_c":8.3,"temp_f":46.9,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":9.4,"wind_kph":15.1,"wind_degree":12,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.3,"precip_mm":0.0,"precip_in":0.0,"humidity":81,"cloud":0,"feelslike_c":5.8,"feelslike_f":42.4,"windchill_c":7.6,"windchill_f":45.6,"heatindex_c":9.7,"heatindex_f":49.5,"dewpoint_c":4.1,"dewpoint_f":39.3,"vis_km":10.0,"vis_miles":6.0,"uv":0.0,"gust_mph":13.3,"gust_kph":21.5,"short_rad":0.08,"diff_rad":0.03,"dni":0.0,"gti":0.03},"forecast":{"forecastday":[{"date":"2025-09-22","date_epoch":1758499200,"day":{"maxtemp_c":16.5,"maxtemp_f":61.8,"mintemp_c":8.9,"mintemp_f":48.1,"avgtemp_c":12.4,"avgtemp_f":54.3,"maxwind_mph":11.4,"maxwind_kph":18.4,"totalprecip_mm":0.0,"totalprecip_in":0.0,"totalsnow_cm":0.0,"avgvis_km":10.0,"avgvis_miles":6.0,"avghumidity":53,"daily_will_it_rain":0,"daily_chance_of_rain":0,"daily_will_it_snow":0,"daily_chance_of_snow":0,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"uv":0.5},"astro":{"sunrise":"06:47 AM","sunset":"06:58 PM","moonrise":"07:26 AM","moonset":"06:57 PM","moon_phase":"Waxing Crescent","moon_illumination":0,"is_moon_up":0,"is_sun_up":0},"hour":[{"time_epoch":1758495600,"time":"2025-09-22 00:00","temp_c":10.2,"temp_f":50.4,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":8.1,"wind_kph":13.0,"wind_degree":19,"wind_dir":"NNE","pressure_mb":1024.0,"pressure_in":30.25,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":68,"cloud":8,"feelslike_c":8.4,"feelslike_f":47.2,"windchill_c":8.4,"windchill_f":47.2,"heatindex_c":10.2,"heatindex_f":50.4,"dewpoint_c":4.5,"dewpoint_f":40.1,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":11.7,"gust_kph":18.8,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758499200,"time":"2025-09-22 01:00","temp_c":9.9,"temp_f":49.8,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":8.1,"wind_kph":13.0,"wind_degree":14,"wind_dir":"NNE","pressure_mb":1025.0,"pressure_in":30.25,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":71,"cloud":20,"feelslike_c":8.0,"feelslike_f":46.4,"windchill_c":8.0,"windchill_f":46.4,"heatindex_c":9.9,"heatindex_f":49.8,"dewpoint_c":4.9,"dewpoint_f":40.7,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":11.8,"gust_kph":18.9,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758502800,"time":"2025-09-22 02:00","temp_c":9.7,"temp_f":49.4,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":8.9,"wind_kph":14.4,"wind_degree":6,"wind_dir":"N","pressure_mb":1024.0,"pressure_in":30.25,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":73,"cloud":11,"feelslike_c":7.6,"feelslike_f":45.7,"windchill_c":7.6,"windchill_f":45.7,"heatindex_c":9.7,"heatindex_f":49.4,"dewpoint_c":5.0,"dewpoint_f":41.0,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":13.3,"gust_kph":21.3,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758506400,"time":"2025-09-22 03:00","temp_c":9.4,"temp_f":48.9,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":8.9,"wind_kph":14.4,"wind_degree":9,"wind_dir":"N","pressure_mb":1025.0,"pressure_in":30.26,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":73,"cloud":11,"feelslike_c":7.3,"feelslike_f":45.1,"windchill_c":7.3,"windchill_f":45.1,"heatindex_c":9.4,"heatindex_f":48.9,"dewpoint_c":4.9,"dewpoint_f":40.7,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":13.4,"gust_kph":21.5,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758510000,"time":"2025-09-22 04:00","temp_c":9.2,"temp_f":48.6,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":9.2,"wind_kph":14.8,"wind_degree":10,"wind_dir":"N","pressure_mb":1025.0,"pressure_in":30.27,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":73,"cloud":6,"feelslike_c":7.0,"feelslike_f":44.6,"windchill_c":7.0,"windchill_f":44.6,"heatindex_c":9.3,"heatindex_f":48.7,"dewpoint_c":4.6,"dewpoint_f":40.4,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":13.9,"gust_kph":22.3,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758513600,"time":"2025-09-22 05:00","temp_c":9.0,"temp_f":48.3,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":9.4,"wind_kph":15.1,"wind_degree":7,"wind_dir":"N","pressure_mb":1026.0,"pressure_in":30.29,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":72,"cloud":6,"feelslike_c":6.7,"feelslike_f":44.1,"windchill_c":6.7,"windchill_f":44.1,"heatindex_c":9.0,"heatindex_f":48.3,"dewpoint_c":4.3,"dewpoint_f":39.8,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":14.3,"gust_kph":23.0,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758517200,"time":"2025-09-22 06:00","temp_c":8.9,"temp_f":48.1,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":9.4,"wind_kph":15.1,"wind_degree":11,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.3,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":72,"cloud":6,"feelslike_c":6.6,"feelslike_f":43.9,"windchill_c":6.6,"windchill_f":43.9,"heatindex_c":9.0,"heatindex_f":48.1,"dewpoint_c":4.2,"dewpoint_f":39.6,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":14.5,"gust_kph":23.3,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758520800,"time":"2025-09-22 07:00","temp_c":8.3,"temp_f":46.9,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":9.4,"wind_kph":15.1,"wind_degree":12,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.3,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":81,"cloud":0,"feelslike_c":7.6,"feelslike_f":45.6,"windchill_c":7.6,"windchill_f":45.6,"heatindex_c":9.7,"heatindex_f":49.5,"dewpoint_c":4.1,"dewpoint_f":39.3,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":13.3,"gust_kph":21.5,"uv":0.0,"short_rad":0.08,"diff_rad":0.03,"dni":0.0,"gti":0.03},{"time_epoch":1758524400,"time":"2025-09-22 08:00","temp_c":11.2,"temp_f":52.2,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":10.1,"wind_kph":16.2,"wind_degree":16,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.33,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":59,"cloud":3,"feelslike_c":9.3,"feelslike_f":48.7,"windchill_c":9.3,"windchill_f":48.7,"heatindex_c":11.2,"heatindex_f":52.2,"dewpoint_c":3.6,"dewpoint_f":38.5,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":12.8,"gust_kph":20.7,"uv":0.1,"short_rad":60.82,"diff_rad":24.19,"dni":1734.64,"gti":15.68},{"time_epoch":1758528000,"time":"2025-09-22 09:00","temp_c":12.9,"temp_f":55.2,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":11.0,"wind_kph":17.6,"wind_degree":21,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.33,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":50,"cloud":2,"feelslike_c":11.2,"feelslike_f":52.2,"windchill_c":11.2,"windchill_f":52.2,"heatindex_c":12.9,"heatindex_f":55.2,"dewpoint_c":2.8,"dewpoint_f":37.1,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":12.9,"gust_kph":20.8,"uv":0.2,"short_rad":135.72,"diff_rad":40.13,"dni":527.3,"gti":4.98},{"time_epoch":1758531600,"time":"2025-09-22 10:00","temp_c":14.1,"temp_f":57.4,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":11.0,"wind_kph":17.6,"wind_degree":26,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.34,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":43,"cloud":0,"feelslike_c":12.7,"feelslike_f":54.9,"windchill_c":12.7,"windchill_f":54.9,"heatindex_c":14.1,"heatindex_f":57.4,"dewpoint_c":1.9,"dewpoint_f":35.4,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":12.6,"gust_kph":20.3,"uv":0.6,"short_rad":211.66,"diff_rad":51.12,"dni":487.59,"gti":0.0},{"time_epoch":1758535200,"time":"2025-09-22 11:00","temp_c":15.0,"temp_f":59.0,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":10.3,"wind_kph":16.6,"wind_degree":24,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.33,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":40,"cloud":18,"feelslike_c":15.0,"feelslike_f":59.0,"windchill_c":15.0,"windchill_f":59.0,"heatindex_c":15.0,"heatindex_f":59.0,"dewpoint_c":1.4,"dewpoint_f":34.5,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":11.8,"gust_kph":19.0,"uv":1.8,"short_rad":281.88,"diff_rad":59.13,"dni":489.66,"gti":0.0},{"time_epoch":1758538800,"time":"2025-09-22 12:00","temp_c":15.8,"temp_f":60.5,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":10.1,"wind_kph":16.2,"wind_degree":20,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.32,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":37,"cloud":6,"feelslike_c":15.8,"feelslike_f":60.5,"windchill_c":15.8,"windchill_f":60.5,"heatindex_c":15.8,"heatindex_f":60.5,"dewpoint_c":1.3,"dewpoint_f":34.3,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":11.6,"gust_kph":18.6,"uv":2.8,"short_rad":342.19,"diff_rad":65.12,"dni":504.06,"gti":0.0},{"time_epoch":1758542400,"time":"2025-09-22 13:00","temp_c":16.4,"temp_f":61.4,"is_day":1,"condition":{"text":"Partly Cloudy ","icon":"//cdn.weatherapi.com/weather/64x64/day/116.png","code":1003},"wind_mph":10.7,"wind_kph":17.3,"wind_degree":18,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.31,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":35,"cloud":46,"feelslike_c":16.4,"feelslike_f":61.4,"windchill_c":16.4,"windchill_f":61.4,"heatindex_c":16.4,"heatindex_f":61.4,"dewpoint_c":0.9,"dewpoint_f":33.7,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":12.3,"gust_kph":19.9,"uv":2.0,"short_rad":389.81,"diff_rad":69.41,"dni":527.77,"gti":0.0},{"time_epoch":1758546000,"time":"2025-09-22 14:00","temp_c":16.5,"temp_f":61.8,"is_day":1,"condition":{"text":"Partly Cloudy ","icon":"//cdn.weatherapi.com/weather/64x64/day/116.png","code":1003},"wind_mph":10.7,"wind_kph":17.3,"wind_degree":16,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.31,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":33,"cloud":46,"feelslike_c":16.5,"feelslike_f":61.8,"windchill_c":16.5,"windchill_f":61.8,"heatindex_c":16.5,"heatindex_f":61.8,"dewpoint_c":0.2,"dewpoint_f":32.4,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":12.3,"gust_kph":19.9,"uv":1.4,"short_rad":621.02,"diff_rad":90.23,"dni":851.73,"gti":0.0},{"time_epoch":1758549600,"time":"2025-09-22 15:00","temp_c":16.5,"temp_f":61.6,"is_day":1,"condition":{"text":"Partly Cloudy ","icon":"//cdn.weatherapi.com/weather/64x64/day/116.png","code":1003},"wind_mph":10.3,"wind_kph":16.6,"wind_degree":19,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.31,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":32,"cloud":46,"feelslike_c":16.5,"feelslike_f":61.6,"windchill_c":16.5,"windchill_f":61.6,"heatindex_c":16.5,"heatindex_f":61.6,"dewpoint_c":-0.2,"dewpoint_f":31.6,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":11.8,"gust_kph":19.0,"uv":1.5,"short_rad":593.06,"diff_rad":87.83,"dni":846.44,"gti":0.0},{"time_epoch":1758553200,"time":"2025-09-22 16:00","temp_c":15.9,"temp_f":60.6,"is_day":1,"condition":{"text":"Partly Cloudy ","icon":"//cdn.weatherapi.com/weather/64x64/day/116.png","code":1003},"wind_mph":11.4,"wind_kph":18.4,"wind_degree":14,"wind_dir":"NNE","pressure_mb":1026.0,"pressure_in":30.31,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":33,"cloud":46,"feelslike_c":15.9,"feelslike_f":60.6,"windchill_c":15.9,"windchill_f":60.6,"heatindex_c":15.9,"heatindex_f":60.6,"dewpoint_c":-0.1,"dewpoint_f":31.8,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":13.8,"gust_kph":22.2,"uv":0.8,"short_rad":550.56,"diff_rad":84.44,"dni":879.54,"gti":0.0},{"time_epoch":1758556800,"time":"2025-09-22 17:00","temp_c":15.0,"temp_f":59.0,"is_day":1,"condition":{"text":"Partly Cloudy ","icon":"//cdn.weatherapi.com/weather/64x64/day/116.png","code":1003},"wind_mph":10.7,"wind_kph":17.3,"wind_degree":16,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.32,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":37,"cloud":48,"feelslike_c":15.0,"feelslike_f":59.0,"windchill_c":15.0,"windchill_f":59.0,"heatindex_c":15.0,"heatindex_f":59.0,"dewpoint_c":0.3,"dewpoint_f":32.6,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":13.9,"gust_kph":22.3,"uv":0.4,"short_rad":494.96,"diff_rad":80.58,"dni":970.58,"gti":0.0},{"time_epoch":1758560400,"time":"2025-09-22 18:00","temp_c":13.8,"temp_f":56.9,"is_day":1,"condition":{"text":"Sunny","icon":"//cdn.weatherapi.com/weather/64x64/day/113.png","code":1000},"wind_mph":9.2,"wind_kph":14.8,"wind_degree":19,"wind_dir":"NNE","pressure_mb":1027.0,"pressure_in":30.33,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":40,"cloud":9,"feelslike_c":12.7,"feelslike_f":54.8,"windchill_c":12.7,"windchill_f":54.8,"heatindex_c":13.8,"heatindex_f":56.9,"dewpoint_c":0.5,"dewpoint_f":32.9,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":12.8,"gust_kph":20.7,"uv":0.1,"short_rad":430.53,"diff_rad":74.3,"dni":1208.15,"gti":0.0},{"time_epoch":1758564000,"time":"2025-09-22 19:00","temp_c":12.7,"temp_f":54.8,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":8.1,"wind_kph":13.0,"wind_degree":34,"wind_dir":"NE","pressure_mb":1028.0,"pressure_in":30.36,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":45,"cloud":6,"feelslike_c":11.4,"feelslike_f":52.6,"windchill_c":11.4,"windchill_f":52.6,"heatindex_c":12.7,"heatindex_f":54.8,"dewpoint_c":1.0,"dewpoint_f":33.8,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":11.7,"gust_kph":18.9,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758567600,"time":"2025-09-22 20:00","temp_c":12.1,"temp_f":53.7,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":6.7,"wind_kph":10.8,"wind_degree":44,"wind_dir":"NE","pressure_mb":1029.0,"pressure_in":30.37,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":48,"cloud":5,"feelslike_c":11.0,"feelslike_f":51.8,"windchill_c":11.0,"windchill_f":51.8,"heatindex_c":12.1,"heatindex_f":53.7,"dewpoint_c":1.3,"dewpoint_f":34.4,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":9.9,"gust_kph":15.9,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758571200,"time":"2025-09-22 21:00","temp_c":11.6,"temp_f":52.9,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":5.8,"wind_kph":9.4,"wind_degree":38,"wind_dir":"NE","pressure_mb":1029.0,"pressure_in":30.38,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":51,"cloud":7,"feelslike_c":10.6,"feelslike_f":51.2,"windchill_c":10.6,"windchill_f":51.2,"heatindex_c":11.6,"heatindex_f":52.9,"dewpoint_c":1.7,"dewpoint_f":35.1,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":8.6,"gust_kph":13.8,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758574800,"time":"2025-09-22 22:00","temp_c":11.3,"temp_f":52.3,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":4.9,"wind_kph":7.9,"wind_degree":42,"wind_dir":"NE","pressure_mb":1029.0,"pressure_in":30.38,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":53,"cloud":6,"feelslike_c":10.6,"feelslike_f":51.0,"windchill_c":10.6,"windchill_f":51.0,"heatindex_c":11.3,"heatindex_f":52.3,"dewpoint_c":2.2,"dewpoint_f":35.9,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":7.1,"gust_kph":11.4,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758578400,"time":"2025-09-22 23:00","temp_c":10.9,"temp_f":51.7,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":3.8,"wind_kph":6.1,"wind_degree":39,"wind_dir":"NE","pressure_mb":1028.0,"pressure_in":30.37,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":56,"cloud":7,"feelslike_c":10.5,"feelslike_f":50.9,"windchill_c":10.5,"windchill_f":50.9,"heatindex_c":10.9,"heatindex_f":51.7,"dewpoint_c":2.5,"dewpoint_f":36.6,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":5.5,"gust_kph":8.9,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0}]},{"date":"2025-09-23","date_epoch":1758585600,"day":{"maxtemp_c":15.9,"maxtemp_f":60.6,"mintemp_c":9.2,"mintemp_f":48.6,"avgtemp_c":12.7,"avgtemp_f":54.8,"maxwind_mph":9.4,"maxwind_kph":15.1,"totalprecip_mm":0.02,"totalprecip_in":0.0,"totalsnow_cm":0.0,"avgvis_km":10.0,"avgvis_miles":6.0,"avghumidity":57,"daily_will_it_rain":0,"daily_chance_of_rain":0,"daily_will_it_snow":0,"daily_chance_of_snow":0,"condition":{"text":"Overcast ","icon":"//cdn.weatherapi.com/weather/64x64/day/122.png","code":1009},"uv":0.7},"astro":{"sunrise":"06:48 AM","sunset":"06:56 PM","moonrise":"08:38 AM","moonset":"07:08 PM","moon_phase":"Waxing Crescent","moon_illumination":1,"is_moon_up":0,"is_sun_up":0},"hour":[{"time_epoch":1758582000,"time":"2025-09-23 00:00","temp_c":10.7,"temp_f":51.2,"is_day":0,"condition":{"text":"Clear ","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":4.0,"wind_kph":6.5,"wind_degree":9,"wind_dir":"N","pressure_mb":1028.0,"pressure_in":30.37,"precip_mm":0.0,"precip_in":0.0,"snow_cm":0.0,"humidity":58,"cloud":6,"feelslike_c":10.1,"feelslike_f":50.2,"windchill_c":10.1,"windchill_f":50.2,"heatindex_c":10.7,"heatindex_f":51.2,"dewpoint_c":2.7,"dewpoint_f":36.8,"will_it_rain":0,"chance_of_rain":0,"will_it_snow":0,"chance_of_snow":0,"vis_km":10.0,"vis_miles":6.0,"gust_mph":6.0,"gust_kph":9.6,"uv":0,"short_rad":0,"diff_rad":0,"dni":0,"gti":0},{"time_epoch":1758585600,"time":"2025-09-23 01:

In [64]:
import json
#преобразуем в тип json
data = json.loads(response)
data

{'location': {'name': 'London',
  'region': 'City of London, Greater London',
  'country': 'United Kingdom',
  'lat': 51.5171,
  'lon': -0.1062,
  'tz_id': 'Europe/London',
  'localtime_epoch': 1758523947,
  'localtime': '2025-09-22 07:52'},
 'current': {'last_updated_epoch': 1758523500,
  'last_updated': '2025-09-22 07:45',
  'temp_c': 8.3,
  'temp_f': 46.9,
  'is_day': 1,
  'condition': {'text': 'Sunny',
   'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
   'code': 1000},
  'wind_mph': 9.4,
  'wind_kph': 15.1,
  'wind_degree': 12,
  'wind_dir': 'NNE',
  'pressure_mb': 1026.0,
  'pressure_in': 30.3,
  'precip_mm': 0.0,
  'precip_in': 0.0,
  'humidity': 81,
  'cloud': 0,
  'feelslike_c': 5.8,
  'feelslike_f': 42.4,
  'windchill_c': 7.6,
  'windchill_f': 45.6,
  'heatindex_c': 9.7,
  'heatindex_f': 49.5,
  'dewpoint_c': 4.1,
  'dewpoint_f': 39.3,
  'vis_km': 10.0,
  'vis_miles': 6.0,
  'uv': 0.0,
  'gust_mph': 13.3,
  'gust_kph': 21.5,
  'short_rad': 0.08,
  'diff_rad': 0.03,
  'dni': 0.0,
  'gti': 0.03},
 'forecast': {'forecastday': [{'date': '2025-09-22',
    'date_epoch': 1758499200,
    'day': {'maxtemp_c': 16.5,
     'maxtemp_f': 61.8,
     'mintemp_c': 8.9,
     'mintemp_f': 48.1,
     'avgtemp_c': 12.4,
     'avgtemp_f': 54.3,
     'maxwind_mph': 11.4,
     'maxwind_kph': 18.4,
     'totalprecip_mm': 0.0,
     'totalprecip_in': 0.0,
     'totalsnow_cm': 0.0,
     'avgvis_km': 10.0,
     'avgvis_miles': 6.0,
     'avghumidity': 53,
     'daily_will_it_rain': 0,
     'daily_chance_of_rain': 0,
     'daily_will_it_snow': 0,
     'daily_chance_of_snow': 0,
     'condition': {'text': 'Sunny',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
      'code': 1000},
     'uv': 0.5},
    'astro': {'sunrise': '06:47 AM',
     'sunset': '06:58 PM',
     'moonrise': '07:26 AM',
     'moonset': '06:57 PM',
     'moon_phase': 'Waxing Crescent',
     'moon_illumination': 0,
     'is_moon_up': 0,
     'is_sun_up': 0},
    'hour': [{'time_epoch': 1758495600,
      'time': '2025-09-22 00:00',
      'temp_c': 10.2,
      'temp_f': 50.4,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 8.1,
      'wind_kph': 13.0,
      'wind_degree': 19,
      'wind_dir': 'NNE',
      'pressure_mb': 1024.0,
      'pressure_in': 30.25,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 68,
      'cloud': 8,
      'feelslike_c': 8.4,
      'feelslike_f': 47.2,
      'windchill_c': 8.4,
      'windchill_f': 47.2,
      'heatindex_c': 10.2,
      'heatindex_f': 50.4,
      'dewpoint_c': 4.5,
      'dewpoint_f': 40.1,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 11.7,
      'gust_kph': 18.8,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758499200,
      'time': '2025-09-22 01:00',
      'temp_c': 9.9,
      'temp_f': 49.8,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 8.1,
      'wind_kph': 13.0,
      'wind_degree': 14,
      'wind_dir': 'NNE',
      'pressure_mb': 1025.0,
      'pressure_in': 30.25,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 71,
      'cloud': 20,
      'feelslike_c': 8.0,
      'feelslike_f': 46.4,
      'windchill_c': 8.0,
      'windchill_f': 46.4,
      'heatindex_c': 9.9,
      'heatindex_f': 49.8,
      'dewpoint_c': 4.9,
      'dewpoint_f': 40.7,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 11.8,
      'gust_kph': 18.9,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758502800,
      'time': '2025-09-22 02:00',
      'temp_c': 9.7,
      'temp_f': 49.4,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 8.9,
      'wind_kph': 14.4,
      'wind_degree': 6,
      'wind_dir': 'N',
      'pressure_mb': 1024.0,
      'pressure_in': 30.25,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 73,
      'cloud': 11,
      'feelslike_c': 7.6,
      'feelslike_f': 45.7,
      'windchill_c': 7.6,
      'windchill_f': 45.7,
      'heatindex_c': 9.7,
      'heatindex_f': 49.4,
      'dewpoint_c': 5.0,
      'dewpoint_f': 41.0,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 13.3,
      'gust_kph': 21.3,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758506400,
      'time': '2025-09-22 03:00',
      'temp_c': 9.4,
      'temp_f': 48.9,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 8.9,
      'wind_kph': 14.4,
      'wind_degree': 9,
      'wind_dir': 'N',
      'pressure_mb': 1025.0,
      'pressure_in': 30.26,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 73,
      'cloud': 11,
      'feelslike_c': 7.3,
      'feelslike_f': 45.1,
      'windchill_c': 7.3,
      'windchill_f': 45.1,
      'heatindex_c': 9.4,
      'heatindex_f': 48.9,
      'dewpoint_c': 4.9,
      'dewpoint_f': 40.7,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 13.4,
      'gust_kph': 21.5,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758510000,
      'time': '2025-09-22 04:00',
      'temp_c': 9.2,
      'temp_f': 48.6,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 9.2,
      'wind_kph': 14.8,
      'wind_degree': 10,
      'wind_dir': 'N',
      'pressure_mb': 1025.0,
      'pressure_in': 30.27,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 73,
      'cloud': 6,
      'feelslike_c': 7.0,
      'feelslike_f': 44.6,
      'windchill_c': 7.0,
      'windchill_f': 44.6,
      'heatindex_c': 9.3,
      'heatindex_f': 48.7,
      'dewpoint_c': 4.6,
      'dewpoint_f': 40.4,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 13.9,
      'gust_kph': 22.3,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758513600,
      'time': '2025-09-22 05:00',
      'temp_c': 9.0,
      'temp_f': 48.3,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 9.4,
      'wind_kph': 15.1,
      'wind_degree': 7,
      'wind_dir': 'N',
      'pressure_mb': 1026.0,
      'pressure_in': 30.29,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 72,
      'cloud': 6,
      'feelslike_c': 6.7,
      'feelslike_f': 44.1,
      'windchill_c': 6.7,
      'windchill_f': 44.1,
      'heatindex_c': 9.0,
      'heatindex_f': 48.3,
      'dewpoint_c': 4.3,
      'dewpoint_f': 39.8,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 14.3,
      'gust_kph': 23.0,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758517200,
      'time': '2025-09-22 06:00',
      'temp_c': 8.9,
      'temp_f': 48.1,
      'is_day': 0,
      'condition': {'text': 'Clear ',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/113.png',
       'code': 1000},
      'wind_mph': 9.4,
      'wind_kph': 15.1,
      'wind_degree': 11,
      'wind_dir': 'NNE',
      'pressure_mb': 1026.0,
      'pressure_in': 30.3,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 72,
      'cloud': 6,
      'feelslike_c': 6.6,
      'feelslike_f': 43.9,
      'windchill_c': 6.6,
      'windchill_f': 43.9,
      'heatindex_c': 9.0,
      'heatindex_f': 48.1,
      'dewpoint_c': 4.2,
      'dewpoint_f': 39.6,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 14.5,
      'gust_kph': 23.3,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1758520800,
      'time': '2025-09-22 07:00',
      'temp_c': 8.3,
      'temp_f': 46.9,
      'is_day': 1,
      'condition': {'text': 'Sunny',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
       'code': 1000},
      'wind_mph': 9.4,
      'wind_kph': 15.1,
      'wind_degree': 12,
      'wind_dir': 'NNE',
      'pressure_mb': 1026.0,
      'pressure_in': 30.3,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 81,
      'cloud': 0,
      'feelslike_c': 7.6,
      'feelslike_f': 45.6,
      'windchill_c': 7.6,
      'windchill_f': 45.6,
      'heatindex_c': 9.7,
      'heatindex_f': 49.5,
      'dewpoint_c': 4.1,
      'dewpoint_f': 39.3,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 13.3,
      'gust_kph': 21.5,
      'uv': 0.0,
      'short_rad': 0.08,
      'diff_rad': 0.03,
      'dni': 0.0,
      'gti': 0.03},
     {'time_epoch': 1758524400,
      'time': '2025-09-22 08:00',
      'temp_c': 11.2,
      'temp_f': 52.2,
      'is_day': 1,
      'condition': {'text': 'Sunny',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
       'code': 1000},
      'wind_mph': 10.1,
      'wind_kph': 16.2,
      'wind_degree': 16,
      'wind_dir': 'NNE',
      'pressure_mb': 1027.0,
      'pressure_in': 30.33,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 59,
      'cloud': 3,
      'feelslike_c': 9.3,
      'feelslike_f': 48.7,
      'windchill_c': 9.3,
      'windchill_f': 48.7,
      'heatindex_c': 11.2,
      'heatindex_f': 52.2,
      'dewpoint_c': 3.6,
      'dewpoint_f': 38.5,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 12.8,
      'gust_kph': 20.7,
      'uv': 0.1,
      'short_rad': 60.82,
      'diff_rad': 24.19,
      'dni': 1734.64,
      'gti': 15.68},
     {'time_epoch': 1758528000,
      'time': '2025-09-22 09:00',
      'temp_c': 12.9,
      'temp_f': 55.2,
      'is_day': 1,
      'condition': {'text': 'Sunny',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
       'code': 1000},
      'wind_mph': 11.0,
      'wind_kph': 17.6,
      'wind_degree': 21,
      'wind_dir': 'NNE',
      'pressure_mb': 1027.0,
      'pressure_in': 30.33,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 50,
      'cloud': 2,
      'feelslike_c': 11.2,
      'feelslike_f': 52.2,
      'windchill_c': 11.2,
      'windchill_f': 52.2,
      'heatindex_c': 12.9,
      'heatindex_f': 55.2,
      'dewpoint_c': 2.8,
      'dewpoint_f': 37.1,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 12.9,
      'gust_kph': 20.8,
      'uv': 0.2,
      'short_rad': 135.72,
      'diff_rad': 40.13,
      'dni': 527.3,
      'gti': 4.98},
     {'time_epoch': 1758531600,
      'time': '2025-09-22 10:00',
      'temp_c': 14.1,
      'temp_f': 57.4,
      'is_day': 1,
      'condition': {'text': 'Sunny',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
       'code': 1000},
      'wind_mph': 11.0,
      'wind_kph': 17.6,
      'wind_degree': 26,
      'wind_dir': 'NNE',
      'pressure_mb': 1027.0,
      'pressure_in': 30.34,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 43,
      'cloud': 0,
      'feelslike_c': 12.7,
      'feelslike_f': 54.9,
      'windchill_c': 12.7,
      'windchill_f': 54.9,
      'heatindex_c': 14.1,
      'heatindex_f': 57.4,
      'dewpoint_c': 1.9,
      'dewpoint_f': 35.4,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 12.6,
      'gust_kph': 20.3,
      'uv': 0.6,
      'short_rad': 211.66,
      'diff_rad': 51.12,
      'dni': 487.59,
      'gti': 0.0},
     {'time_epoch': 1758535200,
      'time': '2025-09-22 11:00',
      'temp_c': 15.0,
      'temp_f': 59.0,
      'is_day': 1,
      'condition': {'text': 'Sunny',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
       'code': 1000},
      'wind_mph': 10.3,
      'wind_kph': 16.6,
      'wind_degree': 24,
      'wind_dir': 'NNE',
      'pressure_mb': 1027.0,
      'pressure_in': 30.33,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 40,
      'cloud': 18,
      'feelslike_c': 15.0,
      'feelslike_f': 59.0,
      'windchill_c': 15.0,
      'windchill_f': 59.0,
      'heatindex_c': 15.0,
      'heatindex_f': 59.0,
      'dewpoint_c': 1.4,
      'dewpoint_f': 34.5,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 11.8,
      'gust_kph': 19.0,
      'uv': 1.8,
      'short_rad': 281.88,
      'diff_rad': 59.13,
      'dni': 489.66,
      'gti': 0.0},
     {'time_epoch': 1758538800,
      'time': '2025-09-22 12:00',
      'temp_c': 15.8,
      'temp_f': 60.5,
      'is_day': 1,
      'condition': {'text': 'Sunny',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png',
       'code': 1000},
      'wind_mph': 10.1,
      'wind_kph': 16.2,
      'wind_degree': 20,
      'wind_dir': 'NNE',
      'pressure_mb': 1027.0,
      'pressure_in': 30.32,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 37,
      'cloud': 6,
      'feelslike_c': 15.8,
      'feelslike_f': 60.5,
      'windchill_c': 15.8,
      'windchill_f': 60.5,
      'heatindex_c': 15.8,
      'heatindex_f': 60.5,
      'dewpoint_c': 1.3,
      'dewpoint_f': 34.3,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 11.6,
      'gust_kph': 18.6,
      'uv': 2.8,
      'short_rad': 342.19,
      'diff_rad': 65.12,
      'dni': 504.06,
      'gti': 0.0},
     {'time_epoch': 1758542400,
      'time': '2025-09-22 13:00',
      'temp_c': 16.4,
      'temp_f': 61.4,
      'is_day': 1,
      'condition': {'text': 'Partly Cloudy ',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
       'code': 1003},
      'wind_mph': 10.7,
      'wind_kph': 17.3,
      'wind_degree': 18,
      'wind_dir': 'NNE',
      'pressure_mb': 1026.0,
      'pressure_in': 30.31,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 35,
      'cloud': 46,
      'feelslike_c': 16.4,
      'feelslike_f': 61.4,
      'windchill_c': 16.4,
      'windchill_f': 61.4,
      'heatindex_c': 16.4,
      'heatindex_f': 61.4,
      'dewpoint_c': 0.9,
      'dewpoint_f': 33.7,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 12.3,
      'gust_kph': 19.9,
      'uv': 2.0,
      'short_rad': 389.81,
      'diff_rad': 69.41,
      'dni': 527.77,
      'gti': 0.0},
     {'time_epoch': 1758546000,
      'time': '2025-09-22 14:00',
      'temp_c': 16.5,
      'temp_f': 61.8,
      'is_day': 1,
      'condition': {'text': 'Partly Cloudy ',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
       'code': 1003},
      'wind_mph': 10.7,
      'wind_kph': 17.3,
      'wind_degree': 16,
      'wind_dir': 'NNE',
      'pressure_mb': 1026.0,
      'pressure_in': 30.31,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 33,
      'cloud': 46,
      'feelslike_c': 16.5,
      'feelslike_f': 61.8,
      'windchill_c': 16.5,
      'windchill_f': 61.8,
      'heatindex_c': 16.5,
      'heatindex_f': 61.8,
      'dewpoint_c': 0.2,
      'dewpoint_f': 32.4,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 12.3,
      'gust_kph': 19.9,
      'uv': 1.4,
      'short_rad': 621.02,
      'diff_rad': 90.23,
      'dni': 851.73,
      'gti': 0.0},
     {'time_epoch': 1758549600,
      'time': '2025-09-22 15:00',
      'temp_c': 16.5,
      'temp_f': 61.6,
      'is_day': 1,
      'condition': {'text': 'Partly Cloudy ',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
       'code': 1003},
      'wind_mph': 10.3,
      'wind_kph': 16.6,
      'wind_degree': 19,
      'wind_dir': 'NNE',
      'pressure_mb': 1026.0,
      'pressure_in': 30.31,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 32,
      'cloud': 46,
      'feelslike_c': 16.5,
      'feelslike_f': 61.6,
      'windchill_c': 16.5,
      'windchill_f': 61.6,
      'heatindex_c': 16.5,
      'heatindex_f': 61.6,
      'dewpoint_c': -0.2,
      'dewpoint_f': 31.6,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 11.8,
      'gust_kph': 19.0,
      'uv': 1.5,
      'short_rad': 593.06,
      'diff_rad': 87.83,
      'dni': 846.44,
      'gti': 0.0},
     {'time_epoch': 1758553200,
      'time': '2025-09-22 16:00',
      'temp_c': 15.9,
      'temp_f': 60.6,
      'is_day': 1,
      'condition': {'text': 'Partly Cloudy ',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
       'code': 1003},
      'wind_mph': 11.4,
      'wind_kph': 18.4,
      'wind_degree': 14,
      'wind_dir': 'NNE',
      'pressure_mb': 1026.0,
      'pressure_in': 30.31,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 33,
      'cloud': 46,
      'feelslike_c': 15.9,
      'feelslike_f': 60.6,
      'windchill_c': 15.9,
      'windchill_f': 60.6,
      'heatindex_c': 15.9,
      'heatindex_f': 60.6,
      'dewpoint_c': -0.1,
      'dewpoint_f': 31.8,
      'will_it_rain': 0,
      'chance_of_rain': 0,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 13.8,
      'gust_kph': 22.2,
      'uv': 0.8,
      'short_rad': 550.56,
      'diff_rad': 84.44,
      'dni': 879.54,
      'gti': 0.0},
     {'time_epoch': 1758556800,
      'time': '2025-09-22 17:00',
      'temp_c': 15.0,
      'temp_f': 59.0,
      'is_day': 1,
      'condition': {'text': 'Partly Cloudy ',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
       'code': 1003},
      'wind_mph': 10.7,
      'wind_kph': 17.3,
      'wind_degree': 16,
      'wind_dir': 'NNE',
      'pressure_mb': 1027.0,
      'pressure_in': 30.32,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,

In [65]:
len(data['forecast']['forecastday'])

2

In [89]:
#получаем датафрейм?выбираем основыне колонки для сохранения

simplified_data = []

for day_data in data['forecast']['forecastday']:
    date = day_data['date']
    
    for hour_data in day_data['hour']:
        simplified_data.append({
            'date': date,
            'time': hour_data['time'],
            'temp_c': hour_data['temp_c'],
            'temp_f': hour_data['temp_f'],
            'condition': hour_data['condition']['text'],
            'humidity': hour_data['humidity'],
            'wind_kph': hour_data['wind_kph']
        })

df_simple = pd.DataFrame(simplified_data)
df_simple.head()

         date              time  temp_c  temp_f condition  humidity  wind_kph
0  2025-09-22  2025-09-22 00:00    10.2    50.4    Clear         68      13.0
1  2025-09-22  2025-09-22 01:00     9.9    49.8    Clear         71      13.0
2  2025-09-22  2025-09-22 02:00     9.7    49.4    Clear         73      14.4
3  2025-09-22  2025-09-22 03:00     9.4    48.9    Clear         73      14.4
4  2025-09-22  2025-09-22 04:00     9.2    48.6    Clear         73      14.8

### Задача 2

Сохраните данные погоды, полученные в предыдущей задаче, в файл `weather.json`. При сохранении используйте четыре пробела для форматирования.

In [97]:
#Запись в файл JSON
df_simple.to_json('weather.json', orient='records', indent=4)

### Задача 3

Из содержимого файла `weather.json` получите **почасовой** прогноз погоды, загрузите его в DataFrame и выведите первые пять строк DataFrame на экран.

In [98]:

#Чтение из JSON в pandas DataFrame
df_s = pd.read_json('weather.json')
df_s.head()

        date              time  temp_c  temp_f condition  humidity  wind_kph
0 2025-09-22  2025-09-22 00:00    10.2    50.4    Clear         68      13.0
1 2025-09-22  2025-09-22 01:00     9.9    49.8    Clear         71      13.0
2 2025-09-22  2025-09-22 02:00     9.7    49.4    Clear         73      14.4
3 2025-09-22  2025-09-22 03:00     9.4    48.9    Clear         73      14.4
4 2025-09-22  2025-09-22 04:00     9.2    48.6    Clear         73      14.8

### Задача 4

Сохраните DataFrame из предыдущей задачи в файл `result.csv`. В качестве названия столбца-индекса используйте `index`.

In [99]:
#сохраняем в формат csv
df_simple.to_csv('result.csv', sep = ',', index_label = 'index')

### Задача 5

Загрузите содержимое SQL-таблицы `ratings` в DataFrame. Выведите первые пять строк DataFrame на экран. Для подключения к БД используйте строку подключения, указанную в следующей ячейке.

In [15]:
import sqlalchemy
import psycopg2
connection = 'postgresql+psycopg2://readonly:6hajV34RTQfmxhS@dsstudents.skillbox.ru:5433/db_ds_students'

connection

'postgresql+psycopg2://readonly:6hajV34RTQfmxhS@dsstudents.skillbox.ru:5433/db_ds_students'

In [8]:

engine = sqlalchemy.create_engine(connection)
connect = engine.connect()

In [12]:
inspector = sqlalchemy.inspect(engine)
inspector.get_table_names()

['links',
 'joi',
 'mobile',
 'new_table',
 'course_purchases',
 'orders',
 'sales',
 'exploratory',
 'studentt',
 'superheroes',
 'users',
 'product_types',
 'products',
 'ratings',
 'keywords',
 'course_purchases_1']

In [14]:
import pandas as pd
connect.rollback()

df = pd.read_sql("SELECT * FROM exploratory", connect)

df.head(5)

OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: https://sqlalche.me/e/20/e3q8)

### Задача 6

Сохраните первые 10000 записей датафрейма из предыдущей задачи в файл `result2.xlsx`, при сохранении задайте листу имя `MySheet`.

(Примечание: для указания имени листа в файле Excel как при чтении, так и при записи используется параметр `sheet_name`)

In [82]:
#сохраняем первые 10000 строк
df.head(10000).to_excel('result2.xlsx', 
                        sheet_name='MySheet',
                        index=False  
                       )

### Задача 7

Определите количество документов в коллекции `users` в MongoDB. Если количество документов < 1000, то в следующей ячейке загрузите всё содержимое этой коллекции в список и выведите нулевой элемент этого списка на экран. Для подключения к MongoDB используйте строку подключения, указанную в следующей ячейке.

In [41]:
import pymongo
#сайт из урока не работает по причине обновления библиотек и python . Взял для работы один из общедоступных сервисов mongodb
conn = 'mongodb://mongo:CLnYghReBBXbijRHTtWsGpHWnDkmEMcN@switchback.proxy.rlwy.net:21133'

In [12]:
!pip install pymongo

Requirement already satisfied: pymongo in c:\users\user0907\appdata\local\anaconda3\lib\site-packages (4.15.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\user0907\appdata\local\anaconda3\lib\site-packages (from pymongo) (2.8.0)

In [42]:
#создание экземпляра класса MongoClient с указанием строки подключения к базе данных MongoDB
client = pymongo.MongoClient(conn)

#выбор базы данных и коллекции
db = client['my_database']

In [43]:
#вызываем метод получения списка имен коллекций
db.list_collection_names()

['users']

In [44]:
#cоздаем/выбираем коллекцию 'users'
collection = db['users']
collection

Collection(Database(MongoClient(host=['switchback.proxy.rlwy.net:21133'], document_class=dict, tz_aware=False, connect=True), 'my_database'), 'users')

In [45]:
#определяем количество документов в коллекции
doc_count = collection.count_documents({})
doc_count

4

In [46]:
#если документов меньше 1000, загружаем всё содержимое
if doc_count < 1000:  
    #получаем все документы и преобразуем курсор в список
    all_documents = list(collection.find())
    
    #выводим документы коллекции
    one_doc = collection.find_one()
    print(one_doc)

    
else:
    print(f"Количество документов ({doc_count}) >= 1000, загрузка не выполняется.")

{'_id': ObjectId('68cc156af8bbe531d31bef0f'), 'name': 'Alice', 'age': 30, 'city': 'Berlin'}

### Задача 8

Преобразуйте список всех документов коллекции `users` из предыдущей задачи в pandas DataFrame и сохраните его содержимое в файл `result3.xlsx`.

In [35]:
#преобразуем курсор в список
head = collection.find()
my_list = list(head)
my_list

[{'_id': ObjectId('68cc156af8bbe531d31bef0f'),
  'name': 'Alice',
  'age': 30,
  'city': 'Berlin'},
 {'_id': ObjectId('68cc156af8bbe531d31bef10'),
  'name': 'Bob',
  'age': 25,
  'city': 'London'},
 {'_id': ObjectId('68cc156af8bbe531d31bef11'),
  'name': 'Charlie',
  'age': 35,
  'city': 'New York'},
 {'_id': ObjectId('68cc156af8bbe531d31bef12'),
  'name': 'Diana',
  'age': 28,
  'city': 'Paris'}]

In [37]:
import pandas as pd
#записываем в датафрейм
df = pd.DataFrame(my_list)
df

                        _id     name  age      city
0  68cc156af8bbe531d31bef0f    Alice   30    Berlin
1  68cc156af8bbe531d31bef10      Bob   25    London
2  68cc156af8bbe531d31bef11  Charlie   35  New York
3  68cc156af8bbe531d31bef12    Diana   28     Paris

In [38]:
#сохраняем в эксель
df.to_excel('result3.xlsx', sheet_name = 'result3', index = 'Insex')

## Дополнительные (необязательные) задачи

### Задача 9

Используя данные SQL-таблицы `ratings`, для каждого пользователя (столбец `userid`) определите средний рейтинг, который этот пользователь поставил фильмам. Результат выведите на экран.

Группировку проведите двумя способами: с помощью `GROUP BY` в строке запроса к БД и с использованием метода `groupby` в pandas.

Для подключения к БД используйте строку подключения в следующей ячейке

In [ ]:
conn = 'postgresql+psycopg2://readonly:6hajV34RTQfmxhS@dsstudents.skillbox.ru:5432/db_ds_students'

### Задача 10

Объедините таблицы `ratings` и `keywords` по столбцам `movieid` (используйте левое объединение). Объединение проведите двумя способами: с помощью `LEFT JOIN` в строке запроса к БД и с использованием метода `merge` в pandas. Результат объединения загрузите в DataFrame и сохраните в файл `result4.csv`.

Обратите внимание, что при объединении возможно дублирование столбцов. В результирующем датафрейме не должно быть таких дублированных столбцов.

In [ ]:
conn = 'postgresql+psycopg2://readonly:6hajV34RTQfmxhS@dsstudents.skillbox.ru:5432/db_ds_students'

### Задача 11

Используя объединенную таблицу из предыдущего задания, найдите все идентификаторы фильмов с тегом `africa` (но не `south africa` или любые другие). Список тегов в формате JSON записан в столбце `tags`.