# Чтение и запись данных

In [1]:
import pandas as pd

## Урок 4. Форматирование дат

### Практика

#### Задание 1.

Скачайте файл Practice3_1.csv, загрузите его в DataFrame с помощью библиотеки pandas и выведите первые 5 строк этого файла на экран. Определите, какой формат дат используется в столбце `Date`. После этого загрузите файл Practice3_1.csv в DataFrame снова, использовав параметры `parse_dates` и `dayfirst`.

In [3]:
df = pd.read_csv('Practice3_1.csv')
df.head(20)

          Date Country    State        City  AvgTemperature
0   01/01/2012      US  Alabama  Birmingham            59.1
1   02/01/2012      US  Alabama  Birmingham            43.0
2   03/01/2012      US  Alabama  Birmingham            30.9
3   04/01/2012      US  Alabama  Birmingham            34.7
4   05/01/2012      US  Alabama  Birmingham            44.1
5   06/01/2012      US  Alabama  Birmingham            46.3
6   07/01/2012      US  Alabama  Birmingham            60.6
7   08/01/2012      US  Alabama  Birmingham            57.4
8   09/01/2012      US  Alabama  Birmingham            59.8
9   10/01/2012      US  Alabama  Birmingham            59.4
10  11/01/2012      US  Alabama  Birmingham            56.4
11  12/01/2012      US  Alabama  Birmingham            46.8
12  13/01/2012      US  Alabama  Birmingham            31.6
13  14/01/2012      US  Alabama  Birmingham            37.7
14  15/01/2012      US  Alabama  Birmingham            44.0
15  16/01/2012      US  Alabama  Birmingham            51.0
16  17/01/2012      US  Alabama  Birmingham            59.3
17  18/01/2012      US  Alabama  Birmingham            50.1
18  19/01/2012      US  Alabama  Birmingham            40.8
19  20/01/2012      US  Alabama  Birmingham            57.9

In [5]:
df = pd.read_csv('Practice3_1.csv', parse_dates=['Date'], dayfirst=True)
df.head(20)

         Date Country    State        City  AvgTemperature
0  2012-01-01      US  Alabama  Birmingham            59.1
1  2012-01-02      US  Alabama  Birmingham            43.0
2  2012-01-03      US  Alabama  Birmingham            30.9
3  2012-01-04      US  Alabama  Birmingham            34.7
4  2012-01-05      US  Alabama  Birmingham            44.1
5  2012-01-06      US  Alabama  Birmingham            46.3
6  2012-01-07      US  Alabama  Birmingham            60.6
7  2012-01-08      US  Alabama  Birmingham            57.4
8  2012-01-09      US  Alabama  Birmingham            59.8
9  2012-01-10      US  Alabama  Birmingham            59.4
10 2012-01-11      US  Alabama  Birmingham            56.4
11 2012-01-12      US  Alabama  Birmingham            46.8
12 2012-01-13      US  Alabama  Birmingham            31.6
13 2012-01-14      US  Alabama  Birmingham            37.7
14 2012-01-15      US  Alabama  Birmingham            44.0
15 2012-01-16      US  Alabama  Birmingham            51.0
16 2012-01-17      US  Alabama  Birmingham            59.3
17 2012-01-18      US  Alabama  Birmingham            50.1
18 2012-01-19      US  Alabama  Birmingham            40.8
19 2012-01-20      US  Alabama  Birmingham            57.9

#### Задание 2.

На основе столбца "Date" создайте новый столбец "Month", который будет содержать _номер месяца_ (от 1 до 12), соответствующего дате в каждой строке. Затем сохраните этот DataFrame в файл MyPractice3_1.csv, используя в качестве разделителя точку с запятой `;`.

In [7]:
df['Month'] = df['Date'].dt.month_name()
df.head()

        Date Country    State        City  AvgTemperature    Month
0 2012-01-01      US  Alabama  Birmingham            59.1  January
1 2012-01-02      US  Alabama  Birmingham            43.0  January
2 2012-01-03      US  Alabama  Birmingham            30.9  January
3 2012-01-04      US  Alabama  Birmingham            34.7  January
4 2012-01-05      US  Alabama  Birmingham            44.1  January

In [9]:
df.to_csv('MyPractice4_1.csv',sep = ';', index_label='index')