# Чтение и запись данных

In [2]:
import pandas as pd

## Урок 2. Чтение файлов в формате CSV

### Практика

#### Задание 1

Откройте файл Practice1_1.csv, загрузите его в DataFrame с помощью библиотеки pandas и выведите первые 5 строк этого файла на экран. Выведите на экран название **предпоследнего** столбца этого файла. Обратите внимание, что при загрузке файла вам может потребоваться явно указать разделитель столбцов.

In [8]:
df = pd.read_csv('Practice1_1.csv', sep = ',')
df.head()

,Date,Country,State,City,AvgTemperature
0,2012-12-02,US,Additional Territories,San Juan Puerto Rico,79.4
1,2012-12-03,US,Additional Territories,San Juan Puerto Rico,77.9
2,2012-12-04,US,Additional Territories,San Juan Puerto Rico,79.8
3,2012-12-05,US,Additional Territories,San Juan Puerto Rico,80.2
4,2012-12-06,US,Additional Territories,San Juan Puerto Rico,78.2

In [9]:
print(df.columns[-2])

City

#### Задание 2.

Откройте файл Practice1_2.csv и загрузите его в DataFrame с помощью библиотеки pandas, указав правильный разделитель столбцов и выбрав столбец-индекс.

In [18]:
df = pd.read_csv('Practice1_2.csv'
                ,sep = ';'
                ,index_col='Date'
                )
df.head()

,Unnamed: 0,Country,State,City,AvgTemperature
Date,,,,,
2012-12-02,56334,US,Additional Territories,San Juan Puerto Rico,79.4
2012-12-03,56335,US,Additional Territories,San Juan Puerto Rico,77.9
2012-12-04,56336,US,Additional Territories,San Juan Puerto Rico,79.8
2012-12-05,56337,US,Additional Territories,San Juan Puerto Rico,80.2
2012-12-06,56338,US,Additional Territories,San Juan Puerto Rico,78.2

#### Задание 3

Откройте файл Practice1_3.csv, загрузите его в DataFrame с помощью библиотеки pandas и выведите первые 5 строк этого файла на экран. Выведите на экран все записи, в которых значение температуры превышает 30 градусов. Обратите внимание, что вам может потребоваться явно указать разделитель столбцов.

In [32]:

df = pd.read_csv('Practice1_3.csv', sep = ',')
result = (df[df['AvgTemperature'] > 30]
          .groupby('City')
          .apply(lambda x: x.sort_values('AvgTemperature', ascending=True))
          .head(20))
print(result)

                     Date Country    State        City  AvgTemperature
City
Birmingham 0   2012-01-03      US  Alabama  Birmingham            30.9
           2   2012-01-13      US  Alabama  Birmingham            31.6
           5   2012-12-27      US  Alabama  Birmingham            34.3
           6   2012-12-30      US  Alabama  Birmingham            34.5
           1   2012-01-04      US  Alabama  Birmingham            34.7
           4   2012-02-13      US  Alabama  Birmingham            34.8
Huntsville 9   2012-01-13      US  Alabama  Huntsville            30.1
           12  2012-02-13      US  Alabama  Huntsville            31.5
           8   2012-01-04      US  Alabama  Huntsville            32.6
           13  2012-12-30      US  Alabama  Huntsville            34.1
           10  2012-02-11      US  Alabama  Huntsville            34.8
Montgomery 15  2012-02-12      US  Alabama  Montgomery            33.3
           14  2012-01-04      US  Alabama  Montgomery            34.3

C:\Users\user0907\AppData\Local\Temp\ipykernel_6708\562328068.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sort_values('AvgTemperature', ascending=True))

In [27]:
result = df[df['AvgTemperature'] > 30].head(20)
print(result)

          Date Country    State        City  AvgTemperature
0   2012-01-03      US  Alabama  Birmingham            30.9
1   2012-01-04      US  Alabama  Birmingham            34.7
2   2012-01-13      US  Alabama  Birmingham            31.6
4   2012-02-13      US  Alabama  Birmingham            34.8
5   2012-12-27      US  Alabama  Birmingham            34.3
6   2012-12-30      US  Alabama  Birmingham            34.5
8   2012-01-04      US  Alabama  Huntsville            32.6
9   2012-01-13      US  Alabama  Huntsville            30.1
10  2012-02-11      US  Alabama  Huntsville            34.8
12  2012-02-13      US  Alabama  Huntsville            31.5
13  2012-12-30      US  Alabama  Huntsville            34.1
14  2012-01-04      US  Alabama  Montgomery            34.3
15  2012-02-12      US  Alabama  Montgomery            33.3